### ISSUE TITLE
Folder mappings in deploy-reloaded?

### ISSUE THREAD

**Issue by DavidA2014** [mkloubert/vscode-deploy-reloaded#113]
I am just wondering why deploy-reloaded does not support folder mappings (which deploy does). Does deploy-reloaded do this in a different way?

**Comment by DavidA2014** [comment]
Any thoughts please?

**Comment by virgilwashere** [comment]
Like the `mappings` in this example target?

https://github.com/mkloubert/vscode-deploy-reloaded#targets-

```json
	"mappings": {
		"/dir/of/files/that/should/be/mapped/**/*": "dir/on/target"
	}
```

**Comment by subz390** [comment]
Exactly - in my project I have `/release/public` folder but on the local WebDAV server I want to put the files in the root of the share.  But with `vscode-deploy-reloaded` I can only put the files in `/release/public` which is so frustrating when everything else about this plugin is awesome.  It's the dealbreaker that will have me looking at another solution because I need the release files in the root, not in a subfolder and I can't put them in the root of my project folder either so they end up in the root of the server.  It's a really awkward situation.

**Comment by DavidA2014** [comment]
@virgilwashere Sorry for this very late reply. The example you showed works for me. Thanks for your help.
