### ISSUE TITLE
Default excluded files / ignores

### ISSUE THREAD

**Issue by kimmenbert** [mkloubert/vscode-deploy-reloaded#30]
Tried looking but couldn't find any reference.
However, it seems like some files are excluded by default. Tried files like .gitignore and .gitattributes. They wouldn't upload even on an explicit deploy file action.

I want to exclude those, so that's good. Is there an overview of the default excluded files?

**Comment by mkloubert** [comment]
@kimmenbert 

**This is a bug.** The correct behavior should be that all files that are inside `.git` folder are ignored by default, not files which start with that expression.

**Should be fixed since 0.53.1.**

I have created a [wiki page](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/ignore_files), which lists all files and folders, that are ignored by default.
