### ISSUE TITLE
Deploying current file works even though current file is not part of any package

### ISSUE THREAD

**Issue by steph643** [mkloubert/vscode-deploy-reloaded#41]
When executing "F1 > Deploy Reloaded: Deploy > Current file", the current file is deployed even though it's not part of any package. Is this the expected behavior? Aren't we supposed to be able to define which files/folders we want to deploy or am I missing the point entirely? How can I prevent files/folders to be deployed by mistake?

My settings:
```json
"deploy.reloaded": {
  "packages": [
    {
      "name": "my-package",
      "files": [
        "my-sub-folder/**"
      ]
      "targets": ["my-target"]
    }
  ],	 
  "targets": [        
    {
      "type": "sftp",
      "name": "my-target",
      ...
    }			
  ]
}
```
With those settings, I expect files from `my-sub-folder` to be deployed, and none other.

My environment:
- Operating system: Windows 7
- Visual Studio Code version: 1.21.0
- Extension version: Deploy (Reloaded) 0.56.0

**Comment by steph643** [comment]
I think I found out what's happening here: my `files` syntax is incorrect and `vscode-deploy` falls silently back to `"files": ["**"]`. 

This raises two questions:
1. What's the `files` syntax to specify a folder?
2. Maybe a syntax error shouldn't fall silently back to default?

**Comment by mkloubert** [comment]
@steph643 

Yes, this is the expected behavior. This makes it possible to deploy files, that are not part of a package. Packages are used to categorize files and deploy multiple files at ones and/or to use auto features like [deploy on save](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/deploy_on_save) or [remove on change](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/remove_on_change).

You can [ignore files](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/ignore_files), to define files and folders that should not be deployed or pulled e.g..

There is no fallback for file patterns. There is a default value: If you do not define `files` property, `**` is used as one and only pattern.

I do not see any mistakes in your pattern definition (maybe the `-` characters?). You can take a look at [minimatch](https://github.com/isaacs/minimatch) and [node-glob](https://github.com/isaacs/node-glob) modules, to get an idea how those patterns work.

**Comment by steph643** [comment]
Thanks, @mkloubert 

I'm still confused about files not part of a package. For those, which target is used when using "F1 > Deploy Reloaded: Deploy > Current file"?

I might have found the origin of my folder issue. The documentation says that "Relative paths are relative to the workspace directory", but it says nothing about [worskpace files](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file). In the case of [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces), it seems that relative paths are relative to their respective root, not to the workspace file. 

If that's the case, it's an issue, because it makes it impossible to select files from one root or another when deploying. For example, in my settings above, what seemed to be wrong is that the `my-sub-folder` element is a root folder, hence out of the file hierarchy.

**Comment by steph643** [comment]
I will create a second issue for the "multi-root workspace" issue.

**Comment by steph643** [comment]
Here it is: https://github.com/mkloubert/vscode-deploy-reloaded/issues/43
