### ISSUE TITLE
Password prompt

### ISSUE THREAD

**Issue by awyl** [mkloubert/vscode-deploy-reloaded#48]
### Description

Just switched from the "classic" version.  Password is not prompted for sftp.  I tried to use the prompt target, but the password is not remembered. 

### Actual behavior

None.

### Expected behavior

Prompt for password when the password is not provided in settings.

**Comment by mkloubert** [comment]
@awyl 

**I have implemented that feature in version 0.62.1**, for [SFTP](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_sftp) and [FTP](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_ftp) targets.

If you do not define an username and/or password (or set them to `(null)`), input boxes are shown and those values are cached by default for the current editor session.

You can control the cache behavior by defining the `alwaysAskForPassword` and/or `alwaysAskForUser` settings.

**Comment by mkloubert** [comment]
@awyl 

Sorry, I forgot to merge from branch.

**The feature should be available since the new version 0.62.2 now.**

**Comment by awyl** [comment]
Thanks for responding so quickly.  Right now it works very well.  I have one more request though.  The password is shown in plain text as we type, can it be masked?

**Comment by mkloubert** [comment]
@awyl 

Sorry, of course! ... **Should be available since version 0.63.0.**

**Comment by awyl** [comment]
Nice!  Work perfectly!!

**Comment by robert914** [comment]
I think I see an issue with this now. I have been using SFTP with a defined "privateKey" setting (i.e. which requires no password), and therefore, I don't have a password defined. However, now every time I start a new season and then use deploy, it now asks for a password. If I just hit "Enter" it happily transfers since it has the privateKey setting, and it stops asking for the current session. However, every new restart of the application or open of a workspace, it asks again.

This password requirement should not happen if the user has a "privateKey" setting, as it won't be needed. I think this is being ignored now for this new password prompt check.

Can you please fix this?

**Comment by mkloubert** [comment]
@robert914 @awyl 

Thanks a lot! **The issue should be fixed since version 0.64.0.**

I there are still issue(s) according to that new feature, you should open a new entry.

**Comment by robert914** [comment]
Works perfect again! Thanks for the fast fix!
