### ISSUE TITLE
beforeDeploy not executed , if no files founds

### ISSUE THREAD

**Issue by FrColin** [mkloubert/vscode-deploy-reloaded#6]
### Description

I go a sftp target , and packages listing files under a dist repositiry
the dist directory is produced by beforeDeploy task.

### Actual behavior

deploy does nothing , since no files found because the dist directory did'nt exist yiet.

### Expected behavior

the deploy should run the beforeDeploy , event if no files found 

### Steps to reproduce

remove the dist repository 

#### Example config

```json
{
    "deploy.reloaded": {
           "packages": [
            {
                "name": "TEST",
                "description": "TEST",
                "files": [
                    "dist/**/*.php",
                    "dist/*.js",
                    "dist/*.css",
                    "dist/*.woff",
                    "dist/*.ttf",
                    "dist/*.svg",
                    "dist/*.woff2",
                    "dist/*.eot",
                    "dist/index.html",
                    "dist/assets/**"
                ],
                "exclude": [
                    "tests/**"
                ],
                "deployOnSave": false,
                "button": {
                    "text": "Deploy",
                    "tooltip": "Click here to deploy to the target...",
                    "targets": [ "TEST" ]
                }

            }
        ],
        "targets": [
            {
                "type": "sftp",
                "name": "TEST",
                "description": "A SFTP folder",
                "dir": "/var/www/test",
                "host": "localhost", "port": 22,
                "user": "root", 
                "beforeDeploy": [
                    {
                        "type": "exec",
                        "command": "npm run prod"
                    }
                ],
    }
}
```

### Your environment

- Operating system: Windows 
- Visual Studio Code version: 1.19.1
- Extension version: 0.15.0

### Additional comments

may be necessary to add some force atribute to the task .

**Comment by mkloubert** [comment]
@FrColin 

**Since version 0.19.0** you can use the new [prepare](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_operations#prepare-) setting, which executes [target operations](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_operations#operations-) before `beforeDeploy` and even if no file is going to be deploy / handeled.

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "prepare": [
                    {
                        "type": "exec",
                        "command": "npm run prod"
                    }
                ]
            }
        ]
    }
}
```

**Comment by FrColin** [comment]
Many thanks, it is working , but I can't see any output of the process ,
is it possible to redirect the output to some window , better near the
Running 'prepare' operation 'exec #1'...

**Comment by FrColin** [comment]
In fact , It doesn't reload the file list after the prepare statement.
my first test was done when some files exist in the dist repository , that let me think that the file was correctly uploaded .
after cleanup of the dist repository and regenerate using the prepare task no files was copied.

**Comment by mkloubert** [comment]
@FrColin 

**Since version 0.20.0** ...

* [prepare operations](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_operations#prepare-) should now reload file list by default, when deploying a [package](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#packages-) e.g.
* [exec](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_operations#exec-) should now print the standard output by default ... if the output is too big, you should try to play with new `maxBuffer` setting

**Comment by FrColin** [comment]
Nice , thanks a lot.
