### ISSUE TITLE
Deploying package which contains files that start with a dot

### ISSUE THREAD

**Issue by eugenkov** [mkloubert/vscode-deploy-reloaded#63]
### Description

When I run deploy package it deploys everything without files that start with a dot (i.e. /subdir/.eslintrc). 
How about add `dot: true` into [DEFAULT_OPTS](https://github.com/mkloubert/vscode-deploy-reloaded/blob/master/src/workspaces.ts#L1258) in method ` findFilesByFilter`?

### Environment

- Operating system: Windows 10 v.1607 build 14393.2007
- Visual Studio Code version: 1.23.1
- Extension version: 0.74.1

**Comment by gencer** [comment]
I hit by same issue.

dotted files does not uploaded and this causes trouble on server side if we change anything.

(Ping @mkloubert)

**Comment by mkloubert** [comment]
@eugenkov @gencer 

No, because this would produce side effects in other deploy environments.

If you are sure that such files have to be updated, you have to open and deploy them by `CTRL + ALT + F`.

**Comment by gencer** [comment]
@mkloubert, I can live with that. Thanks. Just one question. I do not know if this is an expected behavior but when I rename a file, that file uploaded again and remote target has 2 files (old and renamed). Can we make it work with rename? Any setting?

I think this is related: https://github.com/mkloubert/vscode-deploy-reloaded/issues/62

**Comment by gencer** [comment]
Yup found it.:
```
{
    "deploy.reloaded": {
        "removeOnChange": true
    }
}
```

Gencer.
