### ISSUE TITLE
[Buttons] "showPrompt" should default to "true"

### ISSUE THREAD

**Issue by solid-pixel** [mkloubert/vscode-deploy-reloaded#69]
[This section ](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#buttons-) of the Wiki states that the button's setting `showPrompt` should default to `true`, but that is wrong as unless it's manually set to `true`, it will actually default to `false`.

So if I don't manually add this to my settings:

`"showPrompt": true,`

no prompt will appear, and one single misclick will be enough to overwrite your production files.

Instead of amending the wiki, I would set the actual default to `true` - but that's up to you! :)

**Comment by mkloubert** [comment]
@solid-pixel 

Thanks! I fixed the [wiki](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#buttons-) documentation.

The [code](https://github.com/mkloubert/vscode-deploy-reloaded/blob/e625c7196f8b313dbae8fccec9d6966d2cb392dc/src/workspaces.ts#L3740) and the [package.json](https://github.com/mkloubert/vscode-deploy-reloaded/blob/e625c7196f8b313dbae8fccec9d6966d2cb392dc/package.json) uses `(false)` as default, so we should keep that, otherwise some people would wounder about some little "side effects".
