### ISSUE TITLE
Missing 'app' target

### ISSUE THREAD

**Issue by augustozanellato** [mkloubert/vscode-deploy-reloaded#8]
Why was the app target from vscode-deploy removed in this reloaded version?
It's the only reason I didn't switch to this one

**Comment by mkloubert** [comment]
@augustozanellato 

**Since version 0.18.0** the target should be available again.

There were some changes in the API and the usage to make it more clean and powerful, so you should read the [wiki article](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_app) first, before you use and test it.
